// Code generated by Slice Machine. DO NOT EDIT.

import MemberInfo from './MemberInfo/index.svelte';
import SquadInfo from './SquadInfo/index.svelte';

export const components = {
	member_info: MemberInfo,
	squad_info: SquadInfo
};
