// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type MemberDocumentDataSlicesSlice = MemberInfoSlice;

/**
 * Content for member documents
 */
interface MemberDocumentData {
	/**
	 * Slice Zone field in *member*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<MemberDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *member*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: member.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *member*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *member*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: member.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<MemberDocumentData>,
	'member',
	Lang
>;

type SquadDocumentDataSlicesSlice = SquadInfoSlice;

/**
 * Content for squad documents
 */
interface SquadDocumentData {
	/**
	 * Title field in *squad*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Slice Zone field in *squad*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SquadDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *squad*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: squad.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *squad*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *squad*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: squad.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * squad document from Prismic
 *
 * - **API ID**: `squad`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<SquadDocumentData>,
	'squad',
	Lang
>;

export type AllDocumentTypes = MemberDocument | SquadDocument;

/**
 * Primary content in *MemberInfo → Primary*
 */
export interface MemberInfoSliceDefaultPrimary {
	/**
	 * MemberID field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.memberid
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	memberid: prismic.NumberField;

	/**
	 * Name field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Image field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Link field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	link: prismic.KeyTextField;

	/**
	 * GithubHandle field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.githubhandle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	githubhandle: prismic.KeyTextField;

	/**
	 * SquadID field in *MemberInfo → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.primary.squadid
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	squadid: prismic.ContentRelationshipField;
}

/**
 * Primary content in *MemberInfo → Items*
 */
export interface MemberInfoSliceDefaultItem {
	/**
	 * Role field in *MemberInfo → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_info.items[].role
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	role: prismic.KeyTextField;
}

/**
 * Default variation for MemberInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberInfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MemberInfoSliceDefaultPrimary>,
	Simplify<MemberInfoSliceDefaultItem>
>;

/**
 * Slice variation for *MemberInfo*
 */
type MemberInfoSliceVariation = MemberInfoSliceDefault;

/**
 * MemberInfo Shared Slice
 *
 * - **API ID**: `member_info`
 * - **Description**: MemberInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberInfoSlice = prismic.SharedSlice<'member_info', MemberInfoSliceVariation>;

/**
 * Primary content in *SquadInfo → Primary*
 */
export interface SquadInfoSliceDefaultPrimary {
	/**
	 * SquadID field in *SquadInfo → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_info.primary.squadid
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	squadid: prismic.NumberField;

	/**
	 * Name field in *SquadInfo → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_info.primary.name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;
}

/**
 * Default variation for SquadInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadInfoSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SquadInfoSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SquadInfo*
 */
type SquadInfoSliceVariation = SquadInfoSliceDefault;

/**
 * SquadInfo Shared Slice
 *
 * - **API ID**: `squad_info`
 * - **Description**: SquadInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadInfoSlice = prismic.SharedSlice<'squad_info', SquadInfoSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			MemberDocument,
			MemberDocumentData,
			MemberDocumentDataSlicesSlice,
			SquadDocument,
			SquadDocumentData,
			SquadDocumentDataSlicesSlice,
			AllDocumentTypes,
			MemberInfoSlice,
			MemberInfoSliceDefaultPrimary,
			MemberInfoSliceDefaultItem,
			MemberInfoSliceVariation,
			MemberInfoSliceDefault,
			SquadInfoSlice,
			SquadInfoSliceDefaultPrimary,
			SquadInfoSliceVariation,
			SquadInfoSliceDefault
		};
	}
}
